server:
  port : 80
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/GetterzDB?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: Kenem-1257-!
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
credential:
  cryptor:
    master_key: j(^MfTFYeS9ArcNE#)2&&*uU:reX\(&Q
    initial_vector: -@y(c6`V)vqAJc2%
  admin:
    admin_create_key: dare_not_touch_the_sun
e-mail:
  from: kigael16@naver.com
  from-name: Getterz_Mail_Service
  smtp-username: kigael16@naver.com
  smtp-password: kenem-1257-
  host: smtp.naver.com
  port: 465
